# Generated by Django 4.1.4 on 2022-12-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accountid', models.CharField(max_length=100)),
                ('AccountName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contactid', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterestID', models.CharField(max_length=100)),
                ('InterestName', models.CharField(max_length=100)),
                ('InterestType', models.CharField(max_length=100)),
                ('ApprovalStatus', models.CharField(choices=[('Approved', 'Approved'), ('Unapproved', 'Unapproved'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InterestJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterestJunctionID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.CharField(max_length=100)),
                ('ProductName', models.CharField(max_length=100)),
                ('EmailStatus', models.CharField(default='OptIn/OptOut', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllFieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.account')),
                ('Contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.contact')),
                ('Interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.interest')),
                ('InterestJunction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.interestjunction')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.product')),
            ],
        ),
    ]
