# Generated by Django 4.1.4 on 2022-12-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.account')),
                ('Interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.interest')),
            ],
        ),
    ]
