# Generated by Django 4.1.4 on 2022-12-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_junction'),
    ]

    operations = [
        migrations.AddField(
            model_name='junction',
            name='InterestJunctionID',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
