# Generated by Django 4.1.4 on 2022-12-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_junction_interestjunctionid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllFieldData',
        ),
        migrations.DeleteModel(
            name='InterestJunction',
        ),
    ]
